version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"

  bot:
    build: bot/
    command: python3 -u ./main.py ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - postgres